# Generated by Django 5.0.3 on 2024-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0002_alter_studentlogindetails_contact_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactedPersonsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_num', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
