# Generated by Django 5.0.3 on 2024-07-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0003_contactedpersonsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='batch_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
