# Generated by Django 5.0.3 on 2024-07-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_staffdepartments_department_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdepartments',
            name='department_image',
        ),
    ]
