# Generated by Django 5.0.3 on 2024-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='contact_num',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
