# Generated by Django 5.0.3 on 2024-07-09 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_admindetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindetails',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='staffdetails',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='admindetails',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
