# Generated by Django 5.0.3 on 2024-06-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_staffdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='staff_id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
