# Generated by Django 5.0.3 on 2024-07-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0003_studentlogindetails_certification_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogindetails',
            name='fee_cleared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
