# Generated by Django 5.0.3 on 2024-07-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0004_studentlogindetails_fee_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmockinterviews',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentweeklytests',
            name='average_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
